### ISSUE TITLE
Reported Challenge #38362 - update http websites in Baden-Württemberg, Germany

### ISSUE THREAD

**Issue by mvexel** [maproulette/challenge-reports#10]
Challenge: [#38362 - update http websites in Baden-Württemberg, Germany](https://maproulette.org/browse/challenges/38362) 

 Reported by: [Mateusz Konieczny](https://www.openstreetmap.org/user/Mateusz Konieczny)

 This challenge is a massive waste of human time. https://maproulette.org/browse/projects/4233 asks humans to manually review over 227 000 links to check is there https version.

This can, should and is done with automated bot. See https://www.openstreetmap.org/user/b-jazz-bot/history and https://wiki.openstreetmap.org/wiki/Automated_Edits/b-jazz-bot#HTTPS_All_The_Things and https://gitlab.com/b-jazz/https_all_the_things

Doing it manually is utterly pointless and asking people to waste their time. If current bot misses some cases, then bot should be improved.

I tried to contact creator at https://maproulette.org/browse/challenges/38374

ping myself as it will be posted on github: @matkoniecz

**Comment by m-rey** [comment]
(I'm the creator of this maproulette challenge)
thank you for letting me know. I've updated the challenge settings so it isn't discoverable anymore. I hope that solves it.

**Comment by matkoniecz** [comment]
thanks!

what about other https challenges from the same group?

**Comment by m-rey** [comment]
I've configured the project that contains these kind of challenges to not be discoverable. That sould result in the challenges themselves not being discoverable, according to the documentation

**Comment by matkoniecz** [comment]
Then it should be solved
