### ISSUE TITLE
Reported Challenge #39403 - Convert image tag to the wikimedia_commons tag. l GERMANY

### ISSUE THREAD

**Issue by mvexel** [maproulette/challenge-reports#11]
Challenge: [#39403 - Convert image tag to the wikimedia_commons tag. l GERMANY](https://maproulette.org/browse/challenges/39403) 

 Reported by: [googlenaut](https://www.openstreetmap.org/user/googlenaut)

this challenge will remove the view image link in JOSM. :( 
this challenge will remove the view image link in JOSM. :(

**Comment by ivanbranco** [comment]
the challenge doesn't exist anymore, I guess the issue can be closed
