### ISSUE TITLE
Reported Challenge #25460 - Sweden: Missing Buildings

### ISSUE THREAD

**Issue by mvexel** [maproulette/challenge-reports#12]
Challenge: [#25460 - Sweden: Missing Buildings](https://maproulette.org/browse/challenges/25460) 

 Reported by: [Dalkvist](https://www.openstreetmap.org/user/Dalkvist)

Hi, please add an exclusion zone around Kiruna. The town is moving so alot of lots of buildings have been demolished or moved. But they still show up on most imagery, and people have been adding back building that dont exist any more.

examples
https://www.openstreetmap.org/changeset/134005978#map=16/67.8467/20.2290
https://www.openstreetmap.org/changeset/126800509#map=18/67.85200/20.22289

Most up to date imagery (we are allowed to use it as a secondary source, but not integrate it in our tools): https://minkarta.lantmateriet.se/plats/3006/v1.0/?e=719687&n=7535061&z=13&mapprofile=flygbild&background=2&boundaries=false

--
Dalkvist

**Comment by matthiasfeist** [comment]
I just checked and it seems that there are no more challenges in or around Kiruna. I'm not sure if they all have been answered (either "fixed" or some other reply) but at least the map doesn't show them anymore.

**Comment by mvexel** [comment]
The challenge is still active. Is this still a concern?

**Comment by matthiasfeist** [comment]
well the challenge was for all of sweden not only kiruna

**Comment by mvexel** [comment]
Do you think the concern that was raised is valid for the entire challenge? Has the challenge author made any contact that you know of?

**Comment by matthiasfeist** [comment]
Nobody has contacted me directly as far as I know.
Kiruna is a very special case since the whole town is being moved so there will be a lot of mismatches there (also from Sat imagery). 
This should really be a very special scenario that doesn't happen that often in the rest of the world :D

**Comment by mvexel** [comment]
okay, let's leave the challenge alone then. I will close this ticket, but if something else comes up, feel free to contact me again.
