### ISSUE TITLE
Reported Challenge #40307 - USA - Abbreviated Addresses

### ISSUE THREAD

**Issue by mvexel** [maproulette/challenge-reports#14]
Challenge: [#40307 - USA - Abbreviated Addresses](https://maproulette.org/browse/challenges/40307) 

 Reported by: [Mateusz Konieczny](https://www.openstreetmap.org/user/Mateusz Konieczny)

From US Slack

> It tagged a ton of objects in Brooklyn, NY to be "fixed" because it thinks that Avenue N is an abbreviation of "Avenue North". That is most definitely incorrect. And people without checking make changes and mangle correct address tags.
And it's likely that it incorrectly flagged similarly named streets in other locations.

**Comment by mxxcon** [comment]
Looks like the same problem with `Avenue E`. It's trying to rename it to `Avenue East`.

**Comment by atiannicelli** [comment]
I have hidden and archived this challenge. Clearly I need to address (see what I did their?) these issues before I reopen the challenge. Thank you for flagging the challenge!
