### ISSUE TITLE
Reported Challenge #41410 - Use wikimedia_commons tag instead of image tag

### ISSUE THREAD

**Issue by mvexel** [maproulette/challenge-reports#15]
Challenge: [#41410 - Use wikimedia_commons tag instead of image tag](https://maproulette.org/browse/challenges/41410) 

 Reported by: [Mateusz Konieczny](https://www.openstreetmap.org/user/Mateusz Konieczny)

manually done bot edit, instructions do not even pretend that it is mass retagging

violation of https://wiki.openstreetmap.org/wiki/Automated_Edits_code_of_conduct and massive waste of time

it should be discussed and scripted edit rather than asking people to make blindly drudgery edits (only check is checking whether Commons page still exists)

**Comment by Necessarycoot72** [comment]
I thought I closed this challenge after conversing with another user in a changeset. Made it undiscoverable. Hopefully there can be a consensus on the use of wikimedia vs image tag.
