### ISSUE TITLE
Reported Challenge #41822 - Import or merge Feuillette bakeries 🥖 - France #coop

### ISSUE THREAD

**Issue by mvexel** [maproulette/challenge-reports#18]
Challenge: [#41822 - Import or merge Feuillette bakeries 🥖 - France #coop](https://maproulette.org/browse/challenges/41822) 

 Reported by: [confusedbuffalo](https://www.openstreetmap.org/user/confusedbuffalo)

Instructions link to Google Maps and Google Streetview to be used to add shops. This is a clear copyright concern.

**Comment by Binnette** [comment]
I will remove to link to Google 👍️ Mean while I set the project as hidden. TY for reporting 👍️

**Comment by Binnette** [comment]
Challenge "fixed" 👍️
