### ISSUE TITLE
Reported Challenge #29764 - Import or merge B&M shops - France #coop

### ISSUE THREAD

**Issue by mvexel** [maproulette/challenge-reports#22]
Challenge: [#29764 - Import or merge B&M shops - France #coop](https://maproulette.org/browse/challenges/29764) 

 Reported by: [confusedbuffalo](https://www.openstreetmap.org/user/confusedbuffalo)

Instructions have a Google link which takes you to Google maps to be used to add shops. This is a clear copyright concern.

**Comment by Binnette** [comment]
I will remove to link to Google 👍️ Mean while I set the project as hidden. TY for reporting 👍️

**Comment by Binnette** [comment]
Challenge "fixed" 👍️
