### ISSUE TITLE
Reported Challenge #38728 - Add hiking=yes to hiking guidepost - World #QuickFix

### ISSUE THREAD

**Issue by mvexel** [maproulette/challenge-reports#23]
Challenge: [#38728 - Add hiking=yes to hiking guidepost - World #QuickFix](https://maproulette.org/browse/challenges/38728) 

 Reported by: [Mateusz Konieczny](https://www.openstreetmap.org/user/Mateusz Konieczny)

instructions are not even pretending that verification should happen

someone asked about it on chat already so I am not reasking creator

this is just yet another undiscussed bot edit done manually

**Comment by Binnette** [comment]
Challenge deleted 👍️
