### ISSUE TITLE
Challenge #43092 asks for a review of hundreds of objects added confirming to community standards

### ISSUE THREAD

**Issue by jdhoek** [maproulette/challenge-reports#26]
[This challenge](https://maproulette.org/browse/challenges/43092) triggers a review of hundreds of houseboats in Amsterdam where the tagging and geometry seem to be in order. The challenge seems to have been generated from an automated search for buildings in or on water. For `building=houseboat`, being mapped in a body of water is not controversial or wrong, and if any additional tags are desired (e.g., `layer` or `floating=yes`) this should not be done via a MapRoulette challenge with well-meaning mappers 'fixing' these hundreds of objects one by one, but with a single changeset after gaining consensus in the community.

This challenge has raised questions in the Dutch community:

https://community.openstreetmap.org/t/maproulette-challenges-nederlands/108104

Please close this challenge for now.

-----

I have tried to report this issue via the form on the website, but I am getting a 401 bad credentials response in Firefox.

**Comment by mvexel** [comment]
This challenge seems to have been deleted in the meantime.
