### ISSUE TITLE
Reported Challenge #39510 - Latvia - Fix Building and Highway Intersections

### ISSUE THREAD

**Issue by mvexel** [maproulette/challenge-reports#28]
Challenge: [#39510 - Latvia - Fix Building and Highway Intersections](https://maproulette.org/browse/challenges/39510) 

 Reported by: [richlv](https://www.openstreetmap.org/user/richlv)

Hi, the "get in touch" section comes up empty at the MR page, cannot contact the challenge creator.

This challenge seems to have created quite a few problems, see the discussion in https://www.openstreetmap.org/changeset/148551337 .
It would be great to both revisit all the edits, as well as fix the identified problems (using imagery with offset, deleting buildings without an explanation, deleting and re-drawing buildings and more).

**Comment by ChrisPankhurst-TomTom** [comment]
Thank you mvexel for the message, we have seen the feedback by richlv and will look into the issues reported.  Once done and we have a full picture we will then work on the necessary resolutions.

**Comment by mvexel** [comment]
This challenge was already archived, closing
