### ISSUE TITLE
Reported Challenge #48118 - Road reclassification project - GBR

### ISSUE THREAD

**Issue by mvexel** [maproulette/challenge-reports#36]
Challenge: [#48118 - Road reclassification project - GBR](https://maproulette.org/browse/challenges/48118) 

 Reported by: [Mateusz Konieczny](https://www.openstreetmap.org/user/Mateusz%20Konieczny)

specific challenges have broken instructions

see https://community.openstreetmap.org/t/maproulette-critique/116922/62

see https://maproulette.org/challenge/48118/task/229418457 with "challenges description challenges description challenges description challenges description challenges description challenges description challenges description challenges description challenges description challenges description challenges description challenges description challenges description challenges description challenges description challenges description" as of now

**Comment by mvexel** [comment]
Set to non-discoverable. If the author does not respond I'll delete altogether

**Comment by matkoniecz** [comment]
comment was also posted at https://community.openstreetmap.org/t/maproulette-critique/116922/71 (I hope it is fine and welcome to mention it)

**Comment by mvexel** [comment]
Since this challenge was set to private a while ago this can now be closed
