### ISSUE TITLE
Reported Challenge #37540 - India - Add Surface to Highway

### ISSUE THREAD

**Issue by mvexel** [maproulette/challenge-reports#4]
Challenge: [#37540 - India - Add Surface to Highway](https://maproulette.org/browse/challenges/37540) 

 Reported by: [ZeLonewolf](https://www.openstreetmap.org/user/ZeLonewolf)

All motorways are paved.  This challenge is not necessary.  Please see:
https://community.openstreetmap.org/t/maproulette-challenge-add-surface-to-highways-in-california/8200

**Comment by Mapiate** [comment]
Thanks for the feedback. We'll make challenge not discoverable. This will be slightly delayed as most of my colleagues are offline as they work in different timezones; it's already the weekend for them. Once this is completed I'll replay back to this ticket. To prevent this from recurring we'll be seeking community input prior to formally launching a new type of challenge.

**Comment by Mapiate** [comment]
The challenge is no longer discoverable.

**Comment by matkoniecz** [comment]
@mvexel I think it can be closed then?
