### ISSUE TITLE
Reported Challenge #17807 - Invalid turn restriction

### ISSUE THREAD

**Issue by mvexel** [maproulette/challenge-reports#7]
Challenge: [#17807 - Invalid turn restriction](https://maproulette.org/browse/challenges/17807) 

 Reported by: [ivanbranco](https://www.openstreetmap.org/user/ivanbranco)

At least five users commented the challenge, three of them reported that this massive challenge is full of false positive (I also think so). Could the creator of the challenge give a public reply or archive the challenge since it makes a lot of "noise" that makes more difficult for users to find challenges with real problems?

Thanks, looking for a response

**Comment by romwriter** [comment]
Would you mind to archive the challenge without co-operation by the creator of the challenge?

**Comment by mvexel** [comment]
Challenge has been archived and made un-discoverable.
