### ISSUE TITLE
Reported Challenge #38374 - update http websites in Schleswig-Holstein, Germany

### ISSUE THREAD

**Issue by mvexel** [maproulette/challenge-reports#9]
Challenge: [#38374 - update http websites in Schleswig-Holstein, Germany](https://maproulette.org/browse/challenges/38374) 

 Reported by: [Mateusz Konieczny](https://www.openstreetmap.org/user/Mateusz Konieczny)

This challenge is a massive waste of human time. https://maproulette.org/browse/projects/4233 asks humans to manually review over 227 000 links to check is there https version.

This can, should and is done with automated bot. See https://www.openstreetmap.org/user/b-jazz-bot/history and https://wiki.openstreetmap.org/wiki/Automated_Edits/b-jazz-bot#HTTPS_All_The_Things and https://gitlab.com/b-jazz/https_all_the_things

Doing it manually is utterly pointless and asking people to waste their time. If current bot misses some cases, then bot should be improved.

I tried to contact creator at https://maproulette.org/browse/challenges/38374

ping myself in case it will be posted on github: @matkoniecz

**Comment by m-rey** [comment]
(I'm the creator of this maproulette challenge)
thank you for letting me know. I've updated the challenge settings so it isn't discoverable anymore. I hope that solves it.

**Comment by matkoniecz** [comment]
re at https://github.com/maproulette/challenge-reports/issues/10
